import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/globals.css';
import Providers from '@/app/providers';
import Navbar from '@/components/nav/Navbar';

interface Props {
  children: ReactNode;
}

const inter = Inter({ subsets: ['latin'] });

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: Props) => {
  return (
    <Providers>
      <html
        lang='en'
        className='bg-light text-dark dark:bg-dark dark:text-light'
      >
        <body
          className={`${inter.className} flex h-screen flex-col justify-between overscroll-none`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </Providers>
  );
};

export { metadata };
export default RootLayout;
